version: "3.7"

services:
  app:
    build: .
    image: golang:1.16.5
    ports:
      - 3030:3030
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0
    networks:
      - laradock_backend

networks:
  laradock_backend:
    external: true

